export const GET_ALL_CATEGORY = "GET_ALL_CATEGORY"
export const GET_ONE_CATEGORY = "GET_ONE_CATEGORY"
export const CREATE_CATEGORY = "CREATE_CATEGORY"
export const GET_ERROR = "GET_ERROR"

export const GET_ALL_BRAND = "GET_ALL_DRAND"
export const GET_ONE_BRAND = "GET_ONE_BRAND"
export const CREATE_BRAND = "CREATE_DRAND"

export const GET_ALL_SUBCATEGORY = "GET_ALL_SUBCATEGORY"
export const CREATE_SUBCATEGORY = "CREATE_SUBCATEGORY"

export const CREATE_PRODUCT = "CREATE_PRODUCT"
export const GET_ALL_PRODUCT = "GET_ALL_PRODUCT"
export const GET_PRODUCT_DETALIS = "GET_PRODUCT_DETALIS"
export const GET_PRODUCT_SIMILAR = "GET_PRODUCT_SIMILAR"
export const DELETE_PRODUCT = "DELETE_PRODUCT"
